# Generated by Django 4.2.7 on 2023-11-03 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2023, 11, 3, 2, 26, 2, 462770), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='time_create',
            field=models.TimeField(default=datetime.datetime(2023, 11, 3, 2, 26, 2, 462781), verbose_name='Время создания'),
        ),
    ]
