# Generated by Django 4.2.7 on 2023-11-03 02:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0002_alter_applications_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='Status',
            field=models.ForeignKey(default='Новая', null=True, on_delete=django.db.models.deletion.SET_NULL, to='MySite.status'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2023, 11, 3, 2, 44, 13, 145144), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='time_create',
            field=models.TimeField(default=datetime.datetime(2023, 11, 3, 2, 44, 13, 145156), verbose_name='Время создания'),
        ),
    ]
