# Generated by Django 4.2.7 on 2023-11-07 02:27

import MySite.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0002_remove_applications_status_applications_borrower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='design_image',
            field=models.ImageField(default=None, help_text='Разрешается формата файла только jpg, jpeg, png, bmp', null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp']), MySite.models.Applications.validate_image], verbose_name='Дизайн'),
        ),
    ]
