# Generated by Django 4.2.7 on 2023-11-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0004_alter_applications_design_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='comment',
            field=models.TextField(default='something', max_length=1000),
        ),
    ]
